version: "3.0"
services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    # ports:
    #   - 5123:5432
    env_file:
      - .db.env
    volumes:
      - ../pData:/var/lib/postgresql/data

    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 30s
      timeout: 60s
      retries: 10
      start_period: 60s
    networks:
      - microservice

  ts-plugin:
    container_name: ts-plugin
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - microservice
    links:
      - db
    volumes:
      - ../logs:/app/logs
  #      - ./:/home/ts-app

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    networks:
      - microservice
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A user_service worker --loglevel=info --concurrency=20
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - microservice

  celery_beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: celery -A user_service beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - microservice

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    links:
      - ts-plugin
    ports:
      - "0.0.0.0:80:80"
    networks:
      - microservice

networks:
  microservice:
