# Generated by Django 5.1.3 on 2024-12-02 14:36

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('ontology_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None)),
                ('public', models.BooleanField(blank=True, default=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_collections', to='user.usermodel')),
            ],
            options={
                'db_table': 'collections',
            },
        ),
    ]
