# Generated by Django 5.2.5 on 2026-03-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TermDatasetLinkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("curie", models.CharField()),
                ("ontology_id", models.CharField()),
                ("dataset_title", models.CharField()),
            ],
            options={
                "db_table": "term_dataset_links",
            },
        ),
    ]
