# Generated by Django 5.2.5 on 2026-03-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termdatasetlinkmodel',
            name='repo_name',
            field=models.CharField(null=True),
        ),
    ]
