# Generated by Django 5.2.5 on 2026-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts', '0003_termdatasetlinkmodel_dataset_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestFailureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('dataset_title', models.CharField()),
                ('error_code', models.IntegerField()),
            ],
            options={
                'db_table': 'harvest_failures',
            },
        ),
    ]
