# Generated by Django 5.1.3 on 2024-12-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologySuggestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('ontology_purl', models.CharField()),
                ('reason', models.CharField()),
                ('error_logs', models.CharField(blank=True, null=True)),
                ('warning_logs', models.CharField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('collection_id', models.CharField(blank=True, null=True)),
                ('extar_data', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.usermodel')),
            ],
            options={
                'db_table': 'ontology_suggestions',
            },
        ),
    ]
