# Generated by Django 5.1.3 on 2024-12-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('reported_object_type', models.CharField()),
                ('reported_object_id', models.IntegerField()),
                ('report_content', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='pending', null=True)),
                ('client_ts', models.CharField()),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.usermodel')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
