# Generated by Django 5.2.5 on 2026-09-10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ontology",
            fields=[
                (
                    "ontologyId",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("repo_url", models.CharField(max_length=2048)),
                ("definition", models.TextField()),
                ("subjects", models.JSONField(default=list)),
                ("collection", models.JSONField(default=list)),
                ("importsFrom", models.JSONField(default=list)),
                ("exportsTo", models.JSONField(default=list)),
                ("label", models.CharField(max_length=255)),
                ("lang", models.JSONField(default=list)),
                ("loaded", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={"db_table": "ontologies"},
        ),
    ]
