# Generated by Django 5.2.5 on 2026-09-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai_assist", "0001_initial"),
        ("user", "0008_auto_20260123_0958"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiAssistSession",
            fields=[
                ("run_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("workflow", models.CharField(max_length=32)),
                ("context_size", models.PositiveBigIntegerField(default=0)),
                ("prompt_tokens", models.PositiveBigIntegerField(default=0)),
                ("completion_tokens", models.PositiveBigIntegerField(default=0)),
                ("total_tokens", models.PositiveBigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_assist_sessions",
                        to="user.usermodel",
                    ),
                ),
            ],
            options={
                "db_table": "ai_assist_sessions",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="ai_asst_created_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiAssistUserInput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_inputs",
                        to="ai_assist.aiassistsession",
                    ),
                ),
            ],
            options={"db_table": "ai_assist_user_inputs", "ordering": ("sequence",)},
        ),
        migrations.CreateModel(
            name="AiAssistModelOutput",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sequence", models.PositiveIntegerField()),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_outputs",
                        to="ai_assist.aiassistsession",
                    ),
                ),
            ],
            options={"db_table": "ai_assist_model_outputs", "ordering": ("sequence",)},
        ),
        migrations.AddConstraint(
            model_name="aiassistuserinput",
            constraint=models.UniqueConstraint(fields=("session", "sequence"), name="unique_ai_assist_user_input_order"),
        ),
        migrations.AddConstraint(
            model_name="aiassistmodeloutput",
            constraint=models.UniqueConstraint(fields=("session", "sequence"), name="unique_ai_assist_model_output_order"),
        ),
    ]
