# Generated by Django 5.1.3 on 2025-04-01 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_rolemodel_user_alter_usertokenmodel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermSetModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('description', models.CharField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('visibility', models.CharField(default='me')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_term_sets', to='user.usermodel')),
            ],
            options={
                'db_table': 'term_sets',
            },
        ),
        migrations.CreateModel(
            name='TermsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iri', models.CharField()),
                ('term_type', models.CharField()),
                ('metadata', models.JSONField()),
                ('term_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='term_set.termsetmodel')),
            ],
            options={
                'db_table': 'terms',
            },
        ),
    ]
