# Generated by Django 5.1.3 on 2025-04-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('term_set', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsetmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
