# Generated by Django 5.1.3 on 2024-12-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('ontology_id', models.CharField()),
                ('content', models.CharField()),
                ('title', models.CharField()),
                ('client_ts', models.CharField()),
                ('semantic_component_type', models.CharField()),
                ('semantic_component_iri', models.CharField()),
                ('visibility', models.CharField(default='me')),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('pinned', models.BooleanField(blank=True, default=False, null=True)),
                ('parent_ontology_id', models.CharField(blank=True, null=True)),
                ('semantic_component_label', models.CharField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.usermodel')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='NoteCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.CharField()),
                ('active', models.BooleanField(default=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_comments', to='user.usermodel')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_comments', to='note.notemodel')),
            ],
            options={
                'db_table': 'note_comments',
            },
        ),
    ]
