# Generated by Django 5.2.5 on 2025-12-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemodel',
            name='client_ts',
        ),
    ]
