# Generated by Django 5.1.3 on 2024-12-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubIssueRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('ontology_id', models.CharField()),
                ('issue_content', models.CharField()),
                ('issue_title', models.CharField()),
                ('issue_url', models.CharField()),
                ('client_ts', models.CharField()),
                ('issue_type', models.CharField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_github_issues', to='user.usermodel')),
            ],
            options={
                'db_table': 'github_issue_requests',
            },
        ),
    ]
