RUN_REDIS_KEY_PREFIX = "agent"
RUN_GROUP_PREFIX = "agent_run"
RUN_REDIS_KEY_CANCEL = "cancel"
RUN_REDIS_KEY_INPUT = "input"
RUN_REDIS_KEY_READY = "ready"
RUN_REDIS_KEY_STATE = "state"
RUN_REDIS_KEY_RESUMING = "resuming"
RUN_REDIS_KEY_SOCKET_TOKEN = "socket_token"
REDIS_TRUE_VALUE = "1"
RUN_TTL_SECONDS = 3600
READY_TTL_SECONDS = 60
RESUME_TTL_SECONDS = 60
READY_WAIT_TIMEOUT_SECONDS = 30

WEBSOCKET_TOKEN_QUERY_PARAMETER = "token"
WEBSOCKET_TOKEN_BYTES = 32
WEBSOCKET_CLOSE_CODE_UNAUTHORIZED = 4403
WEBSOCKET_CLOSE_CODE_BINARY_UNSUPPORTED = 1003
WEBSOCKET_PATH_TEMPLATE = "/ws/ai_assist/agent/{run_id}/"

CHANNEL_EVENT_TYPE_AGENT_EVENT = "agent.event"
SERVER_MESSAGE_TYPE_CONNECTED = "connected"
SERVER_MESSAGE_TYPE_ERROR = "error"


def run_redis_key(run_id, key):
    return f"{RUN_REDIS_KEY_PREFIX}:{run_id}:{key}"


def run_group_name(run_id):
    return f"{RUN_GROUP_PREFIX}_{run_id}"
