# Generated by Django 5.1.3 on 2024-12-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
