# Generated by Django 5.1.3 on 2025-02-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usermodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='user.usermodel'),
        ),
        migrations.AlterField(
            model_name='usertokenmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ts_token', to='user.usermodel'),
        ),
        migrations.AlterModelTable(
            name='usermodel',
            table='ts_users',
        ),
    ]
