# Generated by Django 5.2.5 on 2025-12-09 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_rolemodel_user_alter_usertokenmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokenmodel',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='usertokenmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_api_keys', to='user.usermodel'),
        ),
        migrations.AlterModelTable(
            name='usertokenmodel',
            table='api_keys',
        ),
    ]
