# Generated by Django 5.2.5 on 2025-12-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_usertokenmodel_expires_at_alter_usertokenmodel_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertokenmodel",
            name="alt_username",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertokenmodel",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usertokenmodel",
            name="name",
            field=models.CharField(default=""),
        ),
    ]
