# Generated by Django 5.2.5 on 2025-12-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_usertokenmodel_alt_username_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usertokenmodel",
            options={"managed": False},
        ),
        migrations.AddField(
            model_name="usermodel",
            name="api_key",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="key_owner",
                to="user.usermodel",
            ),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="title",
            field=models.CharField(blank=True, null=True),
        ),
    ]
