# Generated by Django 5.2.5 on 2026-01-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usertokenmodel_options_usermodel_api_key_and_more'),
    ]

    operations = [
    ]
