# Generated by Django 5.2.5 on 2026-01-23 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20260123_0943'),
    ]

    operations = [
    ]
