# Generated by Django 5.2.5 on 2026-09-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_auto_20260123_0958"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthLoginTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state_hash", models.CharField(max_length=64, unique=True)),
                ("session_key_hash", models.CharField(max_length=64)),
                ("auth_provider", models.CharField(max_length=32)),
                ("client_ts_id", models.CharField(max_length=64)),
                ("code_verifier", models.CharField(blank=True, max_length=128, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "oauth_login_transactions",
                "indexes": [
                    models.Index(fields=["session_key_hash", "expires_at"], name="oauth_login_session_exp_idx"),
                ],
            },
        ),
    ]
