# Generated by Django 5.2.5 on 2026-03-13 07:46

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        TrigramExtension(),
    ]
