# Generated by Django 5.2.5 on 2026-03-13 07:54

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pub_link", "0001_enable_trigram"),
        ("user", "0008_auto_20260123_0958"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubLinkModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doi", models.CharField()),
                ("citation", models.TextField()),
                ("ontology_id", models.CharField()),
                ("created_at", models.DateTimeField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="user.usermodel",
                    ),
                ),
            ],
            options={
                "db_table": "ontology_pub_links",
                "indexes": [
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["citation"],
                        name="citation_index",
                        opclasses=["gin_trgm_ops"],
                    )
                ],
            },
        ),
    ]
